apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 5000  # Exposing port 5000 on the service
      targetPort: http  # This should correspond to the container's "http" port
  type: ClusterIP  # This makes the service accessible only within the Kubernetes cluster
